"""Added column capa in fotos

Revision ID: e56309bb4c37
Revises: 81fdcd43fbab
Create Date: 2026-05-31 18:29:12.912073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e56309bb4c37'
down_revision: Union[str, Sequence[str], None] = '81fdcd43fbab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fotos', sa.Column('capa', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fotos', 'capa')
    # ### end Alembic commands ###
